### ISSUE TITLE
403 when using this plugin with latest ELK stack

### ISSUE THREAD

**Issue by beyond-code-github** [janmg/logstash-input-azure_blob_storage#33]
Hey there,

I am having trouble getting this plugin to work. I've double checked my access key and account names and they're working fine elsewhere. I've tried enabling the debug logging for the plugin but didn't get anything extra out of it. I've also tried using a different container within the account but I get the same error.

I'm using the latest version of the ELK docker repo from here: https://elk-docker.readthedocs.io/

Here are the steps to reproduce:

```
sudo docker run -p 5601:5601 -p 9200:9200  -p 5044:5044     -v elk-data:/var/lib/elasticsearch --name elk sebp/elk -d
docker exec -it elk /bin/bash  #into docker
cd $LOGSTASH_HOME
gosu logstash bin/logstash-plugin install logstash-input-azure_blob_storage
vim 01-azure-block-input.conf

input {
    azure_blob_storage {
        storageaccount => "xxx"
        access_key => "xxxx"
        container => "game-logs"
    }
}

ctrl-d #back to host machine
docker restart elk
```

The container comes back up, starts the pipeline with the new input and then the following errors are present in the logs:

```[2022-10-19T16:14:05,078][ERROR][logstash.javapipeline    ][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::AzureBlobStorage container=>"game-logs", id=>"742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6", storageaccount=>"xxxx", access_key=><password>, enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_af7a915e-d6e7-48fe-9b23-e3b0b227f448", enable_metric=>true, charset=>"UTF-8">, logtype=>"raw", dns_suffix=>"core.windows.net", registry_path=>"data/registry.dat", registry_create_policy=>"resume", interval=>60, addfilename=>false, debug_until=>0, debug_timer=>false, skip_learning=>false, file_head=>"{\"records\":[", file_tail=>"]}", path_filters=>["**/*"]>
  Error: undefined method `each' for nil:NilClass
  Exception: NoMethodError
  Stack: /opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_blob_storage-0.12.4/lib/logstash/inputs/azure_blob_storage.rb:206:in `run'
/opt/logstash/logstash-core/lib/logstash/java_pipeline.rb:410:in `inputworker'
/opt/logstash/logstash-core/lib/logstash/java_pipeline.rb:401:in `block in start_input'
[2022-10-19T16:14:07,107][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] caught: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b55c0204-f01e-0003-5155-e4ab42000000
Time:2022-10-20T07:24:44.3636660Z
[2022-10-19T16:14:07,107][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] loading registry failed for attempt 1 of 3
[2022-10-19T16:14:07,361][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] caught: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b55c02d2-f01e-0003-0155-e4ab42000000
Time:2022-10-20T07:24:44.6185183Z
[2022-10-19T16:14:07,361][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] loading registry failed for attempt 2 of 3
[2022-10-19T16:14:07,616][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] caught: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b55c03a3-f01e-0003-4355-e4ab42000000
Time:2022-10-20T07:24:44.8723721Z
[2022-10-19T16:14:07,616][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] loading registry failed for attempt 3 of 3
[2022-10-19T16:14:07,616][INFO ][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] learn_encapsulation, this can be skipped by setting skip_learning => true. Or set both head_file and tail_file
[2022-10-19T16:14:07,872][INFO ][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] learn json header and footer failed because AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b55c043b-f01e-0003-4a55-e4ab42000000
Time:2022-10-20T07:24:45.1282245Z
[2022-10-19T16:14:07,872][INFO ][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] head will be: {"records":[ and tail is set to ]}
[2022-10-19T16:14:08,126][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] caught: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b55c050d-f01e-0003-0d55-e4ab42000000
Time:2022-10-20T07:24:45.3840773Z for list_blobs retries left 3
[2022-10-19T16:14:08,378][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] caught: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b55c05d6-f01e-0003-4955-e4ab42000000
Time:2022-10-20T07:24:45.6369310Z for list_blobs retries left 2
[2022-10-19T16:14:08,632][ERROR][logstash.inputs.azureblobstorage][main][742b704f496c4aa285833a1faebee4eaaa92e2be70dd78e283a05b52aa3944a6] caught: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b55c069b-f01e-0003-0355-e4ab42000000
Time:2022-10-20T07:24:45.8887867Z for list_blobs retries left 1```

**Comment by beyond-code-github** [comment]
So it turns out I had clock drift in docker which was causing the issue. Sorry to bother you!

**Comment by janmg** [comment]
No worries, it's still useful to help others and to improve error message. Thanks for fixing t and providing the feedback yourself!
